name: Sync staging to production
on:
  workflow_dispatch:
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging -> production
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: production
          github_token: ${{ github.token }}
