name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  test_client:
    name: Test Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install
        run: yarn install --frozen-lockfile # optional, --immutable

      - name: Run Tests
        run: yarn test
